export const landingproductData = [
  {
    name: 'Samurai King Restling',
    category: 'landmarks',
    price: 101,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/1172253/pexels-photo-1172253.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      alt: 'resort',
    },
    bestseller: false,
    featured: true,
    details: {
      dimmentions: {
        width: 1020,
        height: 1020,
      },
      size: 15000,
      description:
        "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely scrambled part of Cicero's De Finibus in order to provide placeholder text to mockup various fonts for a type specimen book.So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely scrambled part of Cicero's De Finibus in order to provide placeholder text to mockup various fonts for a type specimen book.So how did the classical Latin become so incoherent? According to McClintock.",
      recommendations: [
        {
          src: 'https://images.pexels.com/photos/892612/pexels-photo-892612.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
          alt: '',
        },
        {
          src: 'https://images.pexels.com/photos/62689/pexels-photo-62689.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
          alt: '',
        },
        {
          src: 'https://images.pexels.com/photos/7745573/pexels-photo-7745573.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
          alt: '',
        },
      ],
    },
    id: 25,
  },
  {
    name: 'Red Bench',
    category: 'food',
    price: 3.89,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/892612/pexels-photo-892612.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: true,
    featured: false,
    details: null,
    id: 0,
  },
  {
    name: 'Gear',
    category: 'people',
    price: 10,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/62689/pexels-photo-62689.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 1,
  },
  {
    name: 'Floral Shop',
    category: 'cities',
    price: 100,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/7743600/pexels-photo-7743600.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 2,
  },
  {
    name: 'Food',
    category: 'people',
    price: 105,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/1034940/pexels-photo-1034940.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 3,
  },
  {
    name: 'Shed',
    category: 'landmarks',
    price: 290,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/237272/pexels-photo-237272.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 4,
  },
  {
    name: 'Gal',
    category: 'people',
    price: 240,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/1153369/pexels-photo-1153369.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: true,
    featured: false,
    details: null,
    id: 5,
  },
  {
    name: 'Red Juice',
    category: 'food',
    price: 3.89,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/892612/pexels-photo-892612.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: true,
    featured: false,
    details: null,
    id: 6,
  },
  {
    name: 'Red Gear',
    category: 'premium',
    price: 100,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/62689/pexels-photo-62689.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 7,
  },
  {
    name: 'Pet Love',
    category: 'pets',
    price: 100,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/5490235/pexels-photo-5490235.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 8,
  },
  {
    name: 'Floral Dress Ball',
    category: 'people',
    price: 39,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/6135160/pexels-photo-6135160.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: true,
    featured: false,
    details: null,
    id: 12,
  },
  {
    name: 'Red Biking',
    category: 'people',
    price: 50,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/5061172/pexels-photo-5061172.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 13,
  },
  {
    name: 'You Man',
    category: 'people',
    price: 115,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/7745573/pexels-photo-7745573.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 14,
  },
  {
    name: 'Familia',
    category: 'people',
    price: 120,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/1128318/pexels-photo-1128318.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 15,
  },
  {
    name: 'Yoga',
    category: 'nature',
    price: 180,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/7510258/pexels-photo-7510258.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 16,
  },
  {
    name: 'Cam Gal',
    category: 'people',
    price: 290,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/610293/pexels-photo-610293.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: true,
    featured: false,
    details: null,
    id: 17,
  },
  {
    name: 'Big Woman',
    category: 'people',
    price: 100,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/7516356/pexels-photo-7516356.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 9,
  },
  {
    name: 'Palm Shed',
    category: 'place',
    price: 300,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/237272/pexels-photo-237272.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: false,
    featured: false,
    details: null,
    id: 10,
  },
  {
    name: 'New Gal',
    category: 'people',
    price: 200,
    currency: 'USD',
    image: {
      src: 'https://images.pexels.com/photos/1153369/pexels-photo-1153369.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
      alt: '',
    },
    bestseller: true,
    featured: false,
    details: null,
    id: 11,
  },
];

export const fetchData = async () => {
  return Promise.resolve(landingproductData);
};

export const filterData = [
  {
    title: 'Category',
    data: {
      people: { name: 'People', value: 'people', selected: false },
      premium: { name: 'Premium', value: 'premium', selected: false },
      pets: { name: 'Pets', value: 'pets', selected: false },
      food: { name: 'Food', value: 'food', selected: false },
      landmarks: { name: 'Landmarks', value: 'landmarks', selected: false },
      cities: { name: 'Cities', value: 'cities', selected: false },
      nature: { name: 'Nature', value: 'nature', selected: false },
    },
  },
];

export const filterPrice = [
  {
    title: 'Price range',
    data: {
      0: { name: 'less than $20', value: '0', selected: false },
      1: { name: '$20 - $100', value: '1', selected: false },
      2: { name: '$100 - $200', value: '2', selected: false },
      3: { name: '$200 - $300', value: '3', selected: false },
    },
  },
];
